name: "Build & Release"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_release:
    name: Setup & Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Go work
        run: |
          go work init
          go work use .
          go work use ./auth
          go work use ./cache
          go work use ./utils
          go work use ./vip_war
          GOOS=windows GOARCH=amd64 go build -o tone.exe

      - name : sign exe
        run: |
            sudo apt update
            sudo apt install cmake libssl-dev libcurl4-openssl-dev zlib1g-dev python3
            sudo apt install osslsigncode
            osslsigncode sign -pkcs12 tone.pfx -pass 123456 -n "Tone" -i "https://tone.com" -t "http://timestamp.digicert.com" -in tone.exe -out tone_signed.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
              tone_signed.exe
            
            tag_name: v0
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          
